### ISSUE TITLE
Fails in Mac

### ISSUE THREAD

**Issue by marcellodesales** [hypriot/rpi-whoami#2]
```
$ docker run -p 8333:8000 hypriot/rpi-whoami:latest
standard_init_linux.go:175: exec user process caused "no such file or directory"
```

**Comment by Govinda-Fichtner** [comment]
This [issue](https://github.com/docker/docker/issues/23865) describes why this is currently failing. It has nothing to do with the image, but the facts that Docker for Mac needs a Quemu inside the image. 

The aim of this image is to be especially small and lean, that's why it is created from scratch.

**Comment by movpreojects** [comment]
im getting that error running an image with hypriot for pi ON the pi

image from here https://hub.docker.com/r/mycroftai/docker-mycroft/

im not sure if this is an issue with the image or hypriot on pi?

**Comment by firecyberice** [comment]
@movprojects I suppose this image is not built for arm. So you need to port it if you would like to run it on a pi.
